version: "3"

services:
    php:
        image: fauria/lap
        ports:
          - "8080:80"
        volumes:
          - "${WWW_FOLDER}:/var/www/html"
        networks:
          - backend
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: wteamplaner
        MYSQL_USER: wteamplaner
        MYSQL_PASSWORD: wteamplaner
      expose:
        - 3306
      volumes:
        - "${SQL_SCRIPTS_FOLDER}:/docker-entrypoint-initdb.d"
      networks:
        - backend
        
volumes: {}
networks:
  backend: