version: "3"

services:
    php:
        environment:
            LOG_STDOUT: "true"
            LOG_STDERR: "true"
            LOG_LEVEL: debug
        image: fauria/lamp
        ports:
          - "8080:80"
        volumes:
          - "${WWW_FOLDER}:/var/www/html"
        networks:
          - backend
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: resourceplanner
        MYSQL_USER: resourceplanner
        MYSQL_PASSWORD: resourceplanner
      expose:
        - 3306
      volumes:
        - "${SQL_SCRIPTS_FOLDER}:/docker-entrypoint-initdb.d"
      networks:
        - backend
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        PMA_PORT: 3306
        PMA_HOST: "db"
        MYSQL_DATABASE: resourceplanner
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_USER: resourceplanner
        MYSQL_PASSWORD: resourceplanner
      restart: always
      ports:
       - "8081:80"
      networks:
        - backend
        
volumes: {}
networks:
  backend: