

CREATE TABLE Users (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
login VARCHAR(30) NOT NULL,
email VARCHAR(50),
roleflag CHAR(1),
pass VARCHAR(255)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE Entries (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
userId int(6) NOT NULL,
targetDate VARCHAR(10) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

CREATE TABLE Roles (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
role VARCHAR(30) NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;

